CREATE TABLE game_events (
    EVENTID INT,
    EVENTNUM INT,
    GAME_ID INT,
    HOMEDESCRIPTION STRING,
    PCTIMESTRING STRING,
    PERIOD INT,
    PLAYER1_ID INT,
    PLAYER1_NAME STRING,
    PLAYER1_TEAM_ABBREVIATION STRING,
    PLAYER1_TEAM_CITY STRING,
    PLAYER1_TEAM_ID FLOAT,
    PLAYER1_TEAM_NICKNAME STRING,
    PLAYER2_ID INT,
    PLAYER2_NAME STRING,
    PLAYER2_TEAM_ABBREVIATION STRING,
    PLAYER2_TEAM_CITY STRING,
    PLAYER2_TEAM_ID FLOAT,
    PLAYER2_TEAM_NICKNAME STRING,
    PLAYER3_ID INT,
    PLAYER3_NAME STRING,
    PLAYER3_TEAM_ABBREVIATION STRING,
    PLAYER3_TEAM_CITY STRING,
    PLAYER3_TEAM_ID FLOAT,
    PLAYER3_TEAM_NICKNAME STRING,
    SCORE STRING,
    SCOREMARGIN STRING,
    VISITORDESCRIPTION STRING
) 
ROW FORMAT DELIMITED 
FIELDS TERMINATED BY ',' 
STORED AS TEXTFILE 
LOCATION 'hdfs://hive-namenode:8020/user/hive/warehouse/nba.db' 
TBLPROPERTIES ('skip.header.line.count'='1');


WITH game_scores AS (
    SELECT
        GAME_ID,
        PERIOD,
        CAST(SPLIT(SCORE, ' - ')[0] AS INT) AS VISITOR_SCORE,
        CAST(SPLIT(SCORE, ' - ')[1] AS INT) AS HOME_SCORE
    FROM 
        game_events
    WHERE
        SCORE IS NOT NULL AND
        SCORE != '' AND
        PLAYER1_TEAM_ABBREVIATION IS NOT NULL AND
        PLAYER1_TEAM_ABBREVIATION != '' AND
        PERIOD >= 4
),
adjusted_scores AS (
    SELECT
        GAME_ID,
        PERIOD,
        VISITOR_SCORE,
        HOME_SCORE,
        CASE
            WHEN PERIOD = 1 THEN 0
            ELSE VISITOR_SCORE
        END AS ADJUSTED_VISITOR_SCORE,
        CASE
            WHEN PERIOD = 1 THEN 0
            ELSE HOME_SCORE
        END AS ADJUSTED_HOME_SCORE
    FROM game_scores
),
period_min_max AS (
    SELECT
        GAME_ID,
        PERIOD,
        MAX(VISITOR_SCORE) AS MAX_VISITOR_SCORE,
        MIN(ADJUSTED_VISITOR_SCORE) AS MIN_VISITOR_SCORE,
        MAX(HOME_SCORE) AS MAX_HOME_SCORE,
        MIN(ADJUSTED_HOME_SCORE) AS MIN_HOME_SCORE
    FROM adjusted_scores
    GROUP BY GAME_ID, PERIOD
),
period_total AS (
    SELECT
        PERIOD,
        ((MAX_VISITOR_SCORE - MIN_VISITOR_SCORE) + (MAX_HOME_SCORE - MIN_HOME_SCORE)) AS TEAM_POINTS
    FROM period_min_max
)
SELECT PERIOD, ROUND(AVG(TEAM_POINTS)) AS AVG_POINTS
FROM period_total
GROUP BY PERIOD