CREATE TABLE game_events (
    EVENTID INT,
    EVENTNUM INT,
    GAME_ID INT,
    HOMEDESCRIPTION STRING,
    PCTIMESTRING STRING,
    PERIOD INT,
    PLAYER1_ID INT,
    PLAYER1_NAME STRING,
    PLAYER1_TEAM_ABBREVIATION STRING,
    PLAYER1_TEAM_CITY STRING,
    PLAYER1_TEAM_ID FLOAT,
    PLAYER1_TEAM_NICKNAME STRING,
    PLAYER2_ID INT,
    PLAYER2_NAME STRING,
    PLAYER2_TEAM_ABBREVIATION STRING,
    PLAYER2_TEAM_CITY STRING,
    PLAYER2_TEAM_ID FLOAT,
    PLAYER2_TEAM_NICKNAME STRING,
    PLAYER3_ID INT,
    PLAYER3_NAME STRING,
    PLAYER3_TEAM_ABBREVIATION STRING,
    PLAYER3_TEAM_CITY STRING,
    PLAYER3_TEAM_ID FLOAT,
    PLAYER3_TEAM_NICKNAME STRING,
    SCORE STRING,
    SCOREMARGIN STRING,
    VISITORDESCRIPTION STRING
) 
ROW FORMAT DELIMITED 
FIELDS TERMINATED BY ',' 
STORED AS TEXTFILE 
LOCATION 'hdfs://hive-namenode:8020/user/hive/warehouse/nba.db' 
TBLPROPERTIES ('skip.header.line.count'='1');


WITH game_scores AS (
SELECT
    GAME_ID,
    PLAYER1_TEAM_ABBREVIATION AS TEAM_ABBREVIATION,
    SPLIT(SCORE, ' - ')[0] AS SCORE_1,
    SPLIT(SCORE, ' - ')[1] AS SCORE_2,
FROM game_events
WHERE
    SCORE IS NOT NULL AND
    PLAYER1_TEAM_ABBREVIATION IS NOT NULL AND
    SCORE != '' AND
    PLAYER1_TEAM_ABBREVIATION != '' AND
    GAME_ID = 20001116
GROUP BY GAME_ID, PLAYER1_TEAM_ABBREVIATION
)
SELECT
    GAME_ID,
    TEAM_ABBREVIATION,
    MAX(SCORE_1),
    MAX(SCORE_2)
FROM game_scores
GROUP BY GAME_ID, TEAM_ABBREVIATION



WITH
    game_scores AS (
        SELECT
            GAME_ID,
            PLAYER1_TEAM_ABBREVIATION AS TEAM_ABBREVIATION,
            SPLIT(SCORE, ' - ')[0] AS VISITOR_SCORE,
            SPLIT(SCORE, ' - ')[1] AS HOME_SCORE
        FROM game_events
        WHERE
            SCORE IS NOT NULL AND
            SCORE != '' AND
            GAME_ID = 20001116
    ),
    final_score AS (
        SELECT
            GAME_ID,
            TEAM_ABBREVIATION,
            GREATEST(SCORE_1, SCORE_2) AS FINAL_SCORE
        FROM game_scores
    )
SELECT *
FROM final_score
SELECT GAME_ID, TEAM_ABBREVIATION, MAX(FINAL_SCORE)
FROM final_score
GROUP BY GAME_ID, TEAM_ABBREVIATION;



SELECT
GAME_ID,
PLAYER1_TEAM_ABBREVIATION AS TEAM_ABBREVIATION,
SPLIT(SCORE, ' - ')[0] AS SCORE_1,
SPLIT(SCORE, ' - ')[1] AS SCORE_2
FROM game_events
WHERE
SCORE IS NOT NULL AND
PLAYER1_TEAM_ABBREVIATION IS NOT NULL AND
SCORE != '' AND
PLAYER1_TEAM_ABBREVIATION != '' AND
GAME_ID = 20001116;