version: "3.8"

services:
  namenode:
    image: ramilu90/hadoop-namenode
    container_name: cw-namenode
    platform: linux/amd64
    ports:
      - "9870:9870" # Hadoop 3.x Namenode UI
      - "9000:9000" # IPC port
    mem_limit: 256m
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - CLUSTER_NAME=test
    networks:
      - hadoop-net

  datanode:
    image: ramilu90/hadoop-datanode
    container_name: cw-datanode
    platform: linux/amd64
    depends_on:
      - namenode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - CLUSTER_NAME=test
    mem_limit: 256m
    networks:
      - hadoop-net

  resourcemanager:
    image: ramilu90/hadoop-datanode
    container_name: cw-resourcemanager
    platform: linux/amd64
    command: ["yarn", "resourcemanager"]
    depends_on:
      - namenode
      - datanode
    ports:
      - 8088:8088
    mem_limit: 256m
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
    networks:
      - hadoop-net

  nodemanager:
    image: ramilu90/hadoop-datanode
    container_name: cw-nodemanager
    platform: linux/amd64
    command: ["yarn", "nodemanager"]
    mem_limit: 256m
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - YARN_CONF_yarn_nodemanager_resource_memory-mb=256
    networks:
      - hadoop-net

networks:
  hadoop-net:
