version: "3"

services:
  namenode:
    image: apache/zeppelin:0.9.0
    container_name: zeppelin
    platform: linux/amd64
    restart: always
    ports:
      - 8089:8080
    volumes:
      - ./resources:/opt/resources
      - ./scripts:/opt/scripts